---
docker:
  buildkit: true
  from: debian:stretch
  image: tekki/sql-ledger

git:
  repo: https://github.com/Tekki/docker-sql-ledger

global:
  bin: /var/www/sql-ledger
  data: /var/sldata
  datafolders:
    - css
    - images
    - spool
    - templates
    - users
  description: '[SQL-Ledger](https://sql-ledger.com) is an open source ERP and accounting system.'
  license: Artistic-2.0
  group: www-data
  url: sql-ledger
  user: www-data
  title: SQL-Ledger

releases:
  main:
    sha256: 82a78d4b823f3af2853593414e29be30d664e6d281125dd77fda391a7c74b905
    tag: v3.2.09.016
    versions:
      - 3.2.9.16
      - latest
  extended:
    sha256: 1bffc5cec79e8f7980b89abbda0c70d9b403cec390be57b60290966fedd2af35
    tag: v3.2.09.016-e
    versions:
      - 3.2.9.16-e
      - extended
  dws:
    sha256: d1e36c087d153b1a4113d4441e4fc7bc5ec975d8b43d9f4c224f03a095cbc12b
    tag: v3.2.09
    versions:
      - 3.2.9
      - dws

templates:
  - source: docker-entrypoint-sh.ep
    target: docker-entrypoint.sh
  - source: dockerfile.ep
    target: Dockerfile
  - source: sql-ledger-conf.ep
    target: sql-ledger.conf
  - source: sql-ledger-httpd-conf.ep
    target: sql-ledger-httpd.conf
  - source: wlprinter-conf.ep
    target: wlprinter.conf
