---
docker:
  image: tekki/sql-ledger

git:
  repo: https://github.com/Tekki/docker-sql-ledger

global:
  bin: /var/www/sql-ledger
  data: /var/sldata
  datafolders:
    - css
    - images
    - spool
    - templates
    - users
  group: www-data
  url: sql-ledger
  user: www-data

releases:
  main:
    latest: true
    tag: v3.2.07.005
    versions:
      - 3.2.7.5
  extended:
    tag: v3.2.07.005-e
    versions:
      - 3.2.7.5-e
  dws:
    tag: v3.2.07
    versions:
      - 3.2.7

templates:
  - source: docker-entrypoint-sh.ep
    target: docker-entrypoint.sh
  - source: dockerfile.ep
    target: Dockerfile
  - source: sql-ledger-httpd-conf.ep
    target: sql-ledger-httpd.conf
