---
docker:
  buildkit: true
  from: debian:bullseye
  image: tekki/sql-ledger

git:
  repo: https://github.com/Tekki/docker-sql-ledger

global:
  bin: /var/www/sql-ledger
  data: /var/sldata
  datafolders:
    - css
    - images
    - spool
    - templates
    - users
  description: '[SQL-Ledger](https://sql-ledger.com) is an open source ERP and accounting system.'
  license: Artistic-2.0
  group: www-data
  url: sql-ledger
  user: www-data
  title: SQL-Ledger

releases:
  main:
    sha256: 95c8dba159650e1e10ddefd6fc729cd0e008d52c115d9df28408514525d40d07
    tag: v3.2.10.023
    versions:
      - 3.2.10.23
      - latest
  dws:
    sha256: 8e35d86f042e4d18b1096ca7eb687b1068ea385e6d5e2c08e033ba999dc72c8e
    tag: v3.2.10
    versions:
      - 3.2.10
      - dws

templates:
  - source: docker-entrypoint-sh.ep
    target: docker-entrypoint.sh
  - source: dockerfile.ep
    target: Dockerfile
  - source: sql-ledger-conf.ep
    target: sql-ledger.conf
  - source: sql-ledger-httpd-conf.ep
    target: sql-ledger-httpd.conf
  - source: wlprinter-conf.ep
    target: wlprinter.conf
