---
version: '3.8'

services:
  db:
    image: postgres:15
    container_name: sl-db
    environment:
      POSTGRES_PASSWORD: sql-ledger
      POSTGRES_USER: sql-ledger
    volumes:
      - sldb:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: sl-pgadmin
    environment:
      # change these settings or add a new user after the first login:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret
    ports:
      - 8085:80
    volumes:
      - sldbadmin:/var/lib/pgadmin

  app:
    image: tekki/sql-ledger:latest
    container_name: sl-app
    environment:
      SL_HELPFUL_LOGIN: 1
      SL_LOGIN_LANGUAGE: chd_utf
    init: true
    ports:
      - 8080:80
    volumes:
      - sldata:/var/sldata

volumes:
  sldata:
  sldb:
  sldbadmin:
