---
version: '3.7'

services:
  db:
    image: postgres
    container_name: sl-db
    environment:
      POSTGRES_PASSWORD: sql-ledger
      POSTGRES_USER: sql-ledger
    volumes:
      - sldb:/var/lib/postgresql/data

  dbdamin:
    image: adminer
    container_name: sl-dbadmin
    environment:
      ADMINER_DESIGN: nette
    ports:
      - 8081:8080

  app:
    image: tekki/sql-ledger:latest
    container_name: sl-app
    environment:
      SL_HELPFUL_LOGIN: 1
      SL_LOGIN_LANGUAGE: chd_utf
    init: true
    ports:
      - 8080:80
    volumes:
      - sldata:/var/sldata

volumes:
  sldata:
    external: true
  sldb:
    external: true
